managers:
  - name: version
    configuration:
      maintainers:
        - 4n4nd
        - Gkrumbach07
        - Gregory-Pereira
        - harshad16
        - HumairAK
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
